## Fabiolah Jones
## 8/5/2025
## Milestone #3

## Dataset Analysis

In [4]:
import pandas as pd
datafile = pd.read_csv("Perceptions_Of_School_Safety.csv")

### Using .info() we get an overview of the amount of rows/columns and the datatype of the vaules

In [9]:
datafile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Columns: 154 entries, OBJECTID to Shape__Length
dtypes: float64(152), int64(1), object(1)
memory usage: 304.5+ KB

### The dataset as 253 rows and 154 columns

In [8]:
datafile.shape

(253, 154)

### Using .describe() to obtain the statistical summary of the dataset

In [14]:
datafile.describe()

,OBJECTID,Percent_of_7th_Graders_Who_Felt,Percent_of_7th_Graders_Who_Fe_1,Percent_of_7th_Graders_Who_Fe_2,Percent_of_7th_Graders_Who_Fe_3,Percent_of_7th_Graders_Who_Fe_4,Percent_of_9th_Graders_Who_Felt,Percent_of_9th_Graders_Who_Fe_1,Percent_of_9th_Graders_Who_Fe_2,Percent_of_9th_Graders_Who_Fe_3,...,Percent_of_Straight_Students__2,Percent_of_Straight_Students__3,Percent_of_Straight_Students__4,Percent_of_Students_Who_Are_Not,Percent_of_Students_Who_Are_N_1,Percent_of_Students_Who_Are_N_2,Percent_of_Students_Who_Are_N_3,Percent_of_Students_Who_Are_N_4,Shape__Area,Shape__Length
count,253.000000,172.000000,172.000000,172.000000,172.000000,172.000000,116.000000,116.000000,116.000000,116.000000,...,159.000000,159.000000,159.000000,143.000000,143.000000,143.000000,143.000000,143.000000,253.000000,253.000000
mean,127.000000,0.241407,0.445134,0.241023,0.044145,0.028372,0.181879,0.440836,0.307388,0.042362,...,0.268925,0.035950,0.022579,0.240566,0.413769,0.263217,0.045448,0.036993,0.057841,0.985217
std,73.179004,0.076650,0.045504,0.068565,0.024272,0.019165,0.076634,0.062445,0.087922,0.023906,...,0.083329,0.019301,0.015444,0.082757,0.087505,0.080485,0.030967,0.036546,0.144349,0.965138
min,1.000000,0.073000,0.296000,0.094000,0.000000,0.000000,0.036000,0.205000,0.120000,0.000000,...,0.091000,0.000000,0.000000,0.000000,0.154000,0.059000,0.000000,0.000000,0.000004,0.085284
25%,64.000000,0.188500,0.417000,0.194000,0.029000,0.014000,0.130750,0.416250,0.244250,0.028500,...,0.202500,0.025000,0.011000,0.191000,0.375000,0.212500,0.025000,0.014000,0.003929,0.368937
50%,127.000000,0.234000,0.447500,0.240000,0.039000,0.026000,0.167000,0.452500,0.309500,0.037000,...,0.276000,0.034000,0.021000,0.235000,0.418000,0.257000,0.042000,0.029000,0.012476,0.664863
75%,190.000000,0.292500,0.475000,0.289500,0.055000,0.039000,0.230250,0.481250,0.366250,0.051250,...,0.317500,0.045000,0.029500,0.283500,0.460500,0.314500,0.056000,0.044500,0.043436,1.237041
max,253.000000,0.490000,0.632000,0.485000,0.179000,0.108000,0.404000,0.590000,0.575000,0.156000,...,0.470000,0.133000,0.072000,0.500000,0.727000,0.563000,0.185000,0.182000,1.392574,6.370544

### The names of all the columns are as follows:

In [15]:
datafile.columns

Index(['OBJECTID', 'NAME', 'Percent_of_7th_Graders_Who_Felt',
       'Percent_of_7th_Graders_Who_Fe_1', 'Percent_of_7th_Graders_Who_Fe_2',
       'Percent_of_7th_Graders_Who_Fe_3', 'Percent_of_7th_Graders_Who_Fe_4',
       'Percent_of_9th_Graders_Who_Felt', 'Percent_of_9th_Graders_Who_Fe_1',
       'Percent_of_9th_Graders_Who_Fe_2',
       ...
       'Percent_of_Straight_Students__2', 'Percent_of_Straight_Students__3',
       'Percent_of_Straight_Students__4', 'Percent_of_Students_Who_Are_Not',
       'Percent_of_Students_Who_Are_N_1', 'Percent_of_Students_Who_Are_N_2',
       'Percent_of_Students_Who_Are_N_3', 'Percent_of_Students_Who_Are_N_4',
       'Shape__Area', 'Shape__Length'],
      dtype='object', length=154)

### Every value in the dataset is a decimal therefore they datatype that will result for each column is float

In [16]:
datafile.dtypes

OBJECTID                             int64
NAME                                object
Percent_of_7th_Graders_Who_Felt    float64
Percent_of_7th_Graders_Who_Fe_1    float64
Percent_of_7th_Graders_Who_Fe_2    float64
                                    ...
Percent_of_Students_Who_Are_N_2    float64
Percent_of_Students_Who_Are_N_3    float64
Percent_of_Students_Who_Are_N_4    float64
Shape__Area                        float64
Shape__Length                      float64
Length: 154, dtype: object

### The beginning 5 rows and last 5 rows of are displayed below:

In [17]:
datafile.head()

,OBJECTID,NAME,Percent_of_7th_Graders_Who_Felt,Percent_of_7th_Graders_Who_Fe_1,Percent_of_7th_Graders_Who_Fe_2,Percent_of_7th_Graders_Who_Fe_3,Percent_of_7th_Graders_Who_Fe_4,Percent_of_9th_Graders_Who_Felt,Percent_of_9th_Graders_Who_Fe_1,Percent_of_9th_Graders_Who_Fe_2,...,Percent_of_Straight_Students__2,Percent_of_Straight_Students__3,Percent_of_Straight_Students__4,Percent_of_Students_Who_Are_Not,Percent_of_Students_Who_Are_N_1,Percent_of_Students_Who_Are_N_2,Percent_of_Students_Who_Are_N_3,Percent_of_Students_Who_Are_N_4,Shape__Area,Shape__Length
0,1,Taft Union High School District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.079163,2.458127
1,2,Chaffey Joint Union High School District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.029938,1.163191
2,3,Porterville Unified (9-12) School District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000116,0.467513
3,4,William S. Hart Union High School District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.061024,1.334291
4,5,Santa Ynez Valley Union High School District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000345,0.582002

In [18]:
datafile.tail()

,OBJECTID,NAME,Percent_of_7th_Graders_Who_Felt,Percent_of_7th_Graders_Who_Fe_1,Percent_of_7th_Graders_Who_Fe_2,Percent_of_7th_Graders_Who_Fe_3,Percent_of_7th_Graders_Who_Fe_4,Percent_of_9th_Graders_Who_Felt,Percent_of_9th_Graders_Who_Fe_1,Percent_of_9th_Graders_Who_Fe_2,...,Percent_of_Straight_Students__2,Percent_of_Straight_Students__3,Percent_of_Straight_Students__4,Percent_of_Students_Who_Are_Not,Percent_of_Students_Who_Are_N_1,Percent_of_Students_Who_Are_N_2,Percent_of_Students_Who_Are_N_3,Percent_of_Students_Who_Are_N_4,Shape__Area,Shape__Length
248,249,Palm Springs Unified School District,0.197,0.468,0.255,0.048,0.033,0.135,0.442,0.341,...,0.312,0.044,0.028,0.223,0.417,0.303,0.033,0.024,0.126043,1.953879
249,250,Corona-Norco Unified School District,0.339,0.439,0.170,0.034,0.018,0.232,0.475,0.238,...,0.216,0.031,0.015,0.287,0.441,0.211,0.043,0.018,0.036901,1.157824
250,251,Temple City Unified School District,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000926,0.150128
251,252,Arcadia Unified School District,0.360,0.464,0.164,0.006,0.007,0.168,0.551,0.246,...,0.185,0.013,0.005,0.204,0.484,0.280,0.013,0.019,0.003208,0.361184
252,253,Bellflower Unified School District,0.115,0.440,0.355,0.050,0.040,0.069,0.378,0.432,...,0.386,0.046,0.039,0.104,0.429,0.396,0.045,0.026,0.001789,0.204944

### A random row from the dataset is displayed with .sample()

In [20]:
datafile.sample()

,OBJECTID,NAME,Percent_of_7th_Graders_Who_Felt,Percent_of_7th_Graders_Who_Fe_1,Percent_of_7th_Graders_Who_Fe_2,Percent_of_7th_Graders_Who_Fe_3,Percent_of_7th_Graders_Who_Fe_4,Percent_of_9th_Graders_Who_Felt,Percent_of_9th_Graders_Who_Fe_1,Percent_of_9th_Graders_Who_Fe_2,...,Percent_of_Straight_Students__2,Percent_of_Straight_Students__3,Percent_of_Straight_Students__4,Percent_of_Students_Who_Are_Not,Percent_of_Students_Who_Are_N_1,Percent_of_Students_Who_Are_N_2,Percent_of_Students_Who_Are_N_3,Percent_of_Students_Who_Are_N_4,Shape__Area,Shape__Length
135,136,Sweetwater Union High School District,0.214,0.43,0.276,0.047,0.033,0.153,0.436,0.339,...,0.302,0.035,0.024,0.233,0.42,0.265,0.045,0.037,0.039449,1.120566